spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://host.docker.internal:3306/store-reservation-mysql?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    url: jdbc:mysql://localhost:3306/store-reservation?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: storereservation
    password: storereservation

  data:
    redis:
      host: localhost
      port: 6379
